version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    container_name: user-management-database

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - mynetwork
    container_name: user-management-database-server

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb-data:
