openapi: 3.0.0
info:
  title: User management REST API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
      tags:
        - Users
      responses:
        "200":
          description: OK
    post:
      summary: Add a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
                - group_id
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
                group_id:
                  type: integer
      responses:
        "201":
          description: Created
  /users/{id}:
    get:
      summary: Get a user by ID
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
    put:
      summary: Update a user by ID
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
                - group_id
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
                group_id:
                  type: integer
      responses:
        "200":
          description: OK
    delete:
      summary: Delete a user by ID
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: No Content
  /groups:
    get:
      summary: Get all groups
      tags:
        - Groups
      responses:
        "200":
          description: OK
    post:
      summary: Add a new group
      tags:
        - Groups
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "201":
          description: Created
  /groups/{id}:
    get:
      summary: Get a group by ID
      tags:
        - Groups
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
    put:
      summary: Update a group by ID
      tags:
        - Groups
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "200":
          description: OK
    delete:
      summary: Delete a group by ID
      tags:
        - Groups
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: No Content
